In [2]:
import pandas as pd
d_census = pd.read_csv(r'D:\SWP\jupyter_workspace\Interview\BGO\BGO_challenge_census_data.csv')

In [7]:
d_census.sort_values(by=['zcta','year'], ascending=True).sort_index(axis=1)[d_census['zcta'] == 99929]

C:\Users\gubug\AppData\Local\Temp\ipykernel_4268\828128498.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  d_census.sort_values(by=['zcta','year'], ascending=True).sort_index(axis=1)[d_census['zcta'] == 99929]

,B01001A_001E,B01001A_017E,B01001_002E,B01001_026E,B01002_001E,B01002_002E,B01002_003E,B01003_001E,B07009_002E,B07009_003E,...,B25031_001E,B25032_013E,B25036_002E,B25038_009E,B25042_009E,B25056_001E,B25087_001E,B25087_002E,year,zcta
33119,1621,807,1112,1209,44.1,48.3,39.9,2321,146.0,593.0,...,NaN,241,755,241,241,241,755,333,2011,99929
66239,1737,864,1122,1239,50.8,53.9,46.7,2361,158.0,586.0,...,NaN,302,856,302,302,302,856,401,2012,99929
99359,1574,725,1191,1150,53.1,52.9,53.4,2341,195.0,681.0,...,NaN,329,806,329,329,329,806,332,2013,99929
132479,1685,802,1189,1165,54.1,53.9,54.3,2354,200.0,664.0,...,NaN,326,823,326,326,326,823,328,2014,99929
165599,1643,813,1214,1151,50.2,49.9,50.4,2365,178.0,646.0,...,732.0,382,734,382,382,382,734,324,2015,99929
198719,1605,797,1210,1175,48.6,49.4,48.2,2385,210.0,606.0,...,759.0,329,708,329,329,329,708,326,2016,99929
231839,1612,770,1271,1184,49.0,49.5,48.4,2455,205.0,680.0,...,793.0,362,713,362,362,362,713,312,2017,99929
264959,1670,775,1302,1182,49.5,51.6,48.3,2484,219.0,705.0,...,809.0,340,734,340,340,340,734,331,2018,99929
298079,1577,703,1357,1145,49.4,49.7,49.1,2502,259.0,679.0,...,844.0,330,697,330,330,330,697,263,2019,99929
331199,1635,735,1356,1153,47.7,48.7,46.3,2509,220.0,610.0,...,868.0,284,704,284,284,284,704,283,2020,99929
364973,1274,571,1224,937,45.1,43.8,46.5,2161,238.0,577.0,...,938.0,300,541,300,300,300,541,215,2021,99929